### ISSUE TITLE
My Documents Section - Product Name

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#664] opened 2024-03-27 20:06 UTC
### Product

Specification Portal

### Page

Specification Portal

### Description

Under My Documents, the OffsiteSpec.2412 file is listed twice but the Product Names are different. See attached screenshot.

### Expected Behaviour

The Product Name should be the same.
![My Documents_Product Name](https://github.com/Fiserv/Support/assets/101660924/32ed29b7-5a40-4709-b51f-8fbee9e9b9d8)

### Operating system

N/A

### Browser

Google Chrome

**Comment by yanyan-cathy** [comment] 2024-03-27 22:54
I am not able to find OffsiteSpec.2412.All.pdf file under ProprietaryPlatform in the current DEV environment to reproduce the issue, but I tested the other files on the current DEV environment and didn't notice the same issue. If you find any other file has the same issue, please let me know. 

However, in the first entry of OffsiteSpec.2412.All.pdf, it is missing the product name, and this happens when the file is missing from the Github repo but still being added to My documents. Currently,  I am working on this bug fix https://firstdatateam.atlassian.net/browse/PORT-9440 and will give you updates once it is done, thank you!

**Comment by kcaramat** [comment] 2024-03-28 12:23
I replaced OffsiteSpec.2412.All.pdf during my testing and the reason it’s no longer in the DEV environment. Thank you for the update and explaining why the Product Name is missing.

Kristina Caramat
Program Manager
Client Certification
Office: 754.320.7941

Fiserv
World’s Most Admired Companies™ 2024 | Fortune® Magazine
Join us at Forum 2024 | September 29–October 1 <https://www.fiserv.com/en/forum.html?cid=link|outlook|forum2024||emailsignature>
Fiserv<https://www.fiserv.com/?cid=link|fiservsignature|fiservlink||> | Join Our Team<https://www.careers.fiserv.com/?utm_source=outlook&utm_medium=email&utm_campaign=signature> | LinkedIn<https://www.linkedin.com/company/fiserv/> | Facebook | Instagram
<https://www.facebook.com/Fiserv/>
©2024 Fiserv Inc. or its affiliates. Fiserv is a registered trademark of Fiserv Inc. Privacy Notice
<https://www.fiserv.com/en/about-fiserv/privacy-notice.html?cid=link|fiservsignature|privacypolicy||>From Fortune. ©2024 Fortune Media IP Limited. All rights reserved. Used under license.

**Comment by yanyan-cathy** [comment] 2024-05-01 16:03
tenant agreed to close it since the bug can't be reproduced

**Closed as completed by yanyan-cathy** 2024-05-01 16:03 UTC
Labels: bug
