### ISSUE TITLE
Download postman collection functionality and api specs not working [Product QA SilverCore]

### ISSUE THREAD

**Issue by FranciscoCampos09** [Fiserv/Support#515] opened 2023-09-14 16:41 UTC
Hello team, I have a problem when executing the download, it just shows an error attached image:

![image](https://github.com/Fiserv/Support/assets/120739273/2e0cfcbe-49ff-4c03-ae58-75e0c01fdabc)

I already tried with other example products and it only happens to me in silvercore

**Comment by sfiserv** [comment] 2023-09-14 18:05
@FranciscoCampos09 Team is looking into this issue and have found the root cause. We will get it fixed and update you here to validate.

**Comment by FranciscoCampos09** [comment] 2023-09-14 18:15
Thank you very much, I look forward to any support

**Comment by sfiserv** [comment] 2023-09-21 15:37
@FranciscoCampos09  we are making changes to the our database to resolve this issue. This will be resolved in our next QA release.
thank you.

**Comment by sfiserv** [comment] 2023-10-11 21:53
@FranciscoCampos09 The fix is available in QA environment. please validate the functionality is working. Close the issue if fix works as expected.

**Comment by sfiserv** [comment] 2023-10-19 22:42
closing this ticket considering as done.

**Closed by sfiserv** 2023-10-19 22:42 UTC
Labels: bug, SilverCore, client verification
