### ISSUE TITLE
Unable to create a PR from Develop to Stage Branch

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#761] opened 2024-10-22 21:01 UTC
### Product

Reporting

### Page

https://github.com/Fiserv/reporting/compare/stage...develop

### Description

There are multiple file changes from Develop to Stage branches of Reporting Product. But when I create the PR , I don't see any changes being there. 

### Expected Behaviour

There should be changes when I am creating the PR from develop branch to Stage branch

### Operating system

macOS

### Browser

Google chrome

**Comment by minh-pham1** [comment] 2024-10-22 21:17
It seems you already synced `develop`, `stage`, and `main` 5 hours ago.

**Comment by kongaravinatha** [comment] 2024-10-22 21:57
@minh-pham1 
Stage I havenot made any changes and didnot create any PR earlier.

**Comment by minh-pham1** [comment] 2024-10-22 23:22
zpr 151 is a full merge from `develop` -> `stage` which appears to have pulled all 3 changes.

**Comment by minh-pham1** [comment] 2024-10-30 17:26
I'll close this ticket since I'm not sure if the issue was identified. Please feel free to open a new one or reach out on Teams in our `Feedback and Help` channel if the issue is still pertinent.

**Closed by minh-pham1** 2024-10-30 17:26 UTC
Labels: bug
