### ISSUE TITLE
Page not refreshing after selecting a version

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#312] opened 2023-02-14 19:24 UTC
# Reporting new issue for refresh page (FirstVision LATAM)

**Region** (if applicable)
LATAM

**Page**
[Path of the page where the problem exists.](https://dev-developerstudio.fiserv.com/product/FirstVisionLATAM/api/?type=post&path=/account/add-L8V3&branch=develop&version=1.1.0)

**Describe the bug**
When Select a different version it refresh the endpoint but not the menu on the left.

**To Reproduce**
1. Go to any endpoint
2. Click on another version
3. Refresh only the endpoint
4. If the endpoint does not exist in previous version left the endpoint space with no information
![image](https://user-images.githubusercontent.com/111396588/218836797-0721b34b-80c2-4474-84df-26520bb36e1e.png)

**Expected behavior**
1. Go to any endpoint
2. Click on another version
3. Refresh the endpoint and the menu to see only the endpoints related to the selected version

![image](https://user-images.githubusercontent.com/111396588/218836531-1038514e-33d3-49f3-a22e-0f3305a9eb98.png)

**Additional context**

**Comment by sfiserv** [comment] 2023-02-16 19:13
@CinthyaRivera I think the issue is now fixed for your product hence closing this ticket.

**Closed by sfiserv** 2023-02-16 19:13 UTC
Labels: bug
