### ISSUE TITLE
Request Schema's input boxes are initialized with incorrect values

### ISSUE THREAD

**Issue by anamayjmacabuhay** [Fiserv/Support#80] opened 2022-01-20 16:32 UTC
# Reporting new issue for [Ana Macabuhay] (AllData Aggregation)

**Page**
All the APIs under API Explorer of AllData Aggregation page

**Describe the bug**
The initial values displayed in the input boxes of the Response Schema are incorrect; it does not reflect the values that are actually in the Default Response payload. This happens in all the APIs of AllData Aggregation.

**To Reproduce**
Note: for this, we'll be using the getAccountDetails API as an example scenario

1. Go to 'https://qa-developerstudio.fiserv.com/product/AllDataAggregation/api/?type=post&path=/WealthManagementWeb/ws/AccountDataInq/getAccountDetails'
2. Expand 'SignonRq' section of the Request Schema, then expand 'UserInfo'.
3. Click on 'HomeID' section.
4. See that that value in input box is 'version1' while the correct value '50040001' highlighted in the Request payload is displayed.

**Expected behavior**
The values in the input boxes of Request Schema should reflect the correct default values that is also used in the Request payload.

**Screenshots**
![image](https://user-images.githubusercontent.com/95615056/150381018-f0d498e0-60f1-4731-a2f9-ae76ca5827f3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 97.0.4692.71

**Tablet (please complete the following information):**
Not tested on tablet

**Smartphone (please complete the following information):**
Not tested on smartphone

**Additional context**
This happens with various values within the different APIs.

**Comment by OZ-FS** [comment] 2022-01-20 21:11
https://firstdatateam.atlassian.net/browse/PORT-3161 - story for sprint 2 assigned to dongyao.ling@fiserv.com

**Comment by OZ-FS** [comment] 2022-01-26 17:52
The issue is fixed and tested in dev. 
Please validate.

**Closed** 2022-01-27 16:33 UTC
Labels: bug, AllData Aggregation
