### ISSUE TITLE
Request and Response body  in API Reference not visible

### ISSUE THREAD

**Issue by palanikumarfiserv** [Fiserv/Support#453] opened 2023-08-03 09:50 UTC
**Step to reproduce the issue**

Documentation ==> API Reference ==>> Board Account

*This is issue is for all the API's in API Reference unable to see request and response body.
whereas in production it's displaying correctly.

Issue in Environment: QA and Stage portal issue
https://qa-developerstudio.fiserv.com
https://stage-developerstudio.fiserv.com

![reqissue](https://github.com/Fiserv/Support/assets/91948280/c8902547-8ccd-4319-9b69-c93ab132d8fd)

Existing screenshot request and response body where displayed correctly.

![reqrespissue](https://github.com/Fiserv/Support/assets/91948280/1076a038-ecff-4757-8180-e451944a0d33)

**Comment by sfiserv** [comment] 2023-08-09 04:22
This is currently getting fixed. We will update you once it is available for your verification

**Comment by OZ-FS** [comment] 2023-08-28 18:41
Checked production: opened Documentation in light & dark mode for the following document:
https://developer.fiserv.com/product/FirstVisionAPAC/docs/?path=docs/APIs/Account-Management/Board-Account.md&branch=main#tab-response

It appears the issue is fixed:
<img width="1090" alt="Screenshot 2023-08-28 at 11 39 40 AM" src="https://github.com/Fiserv/Support/assets/92183615/96aabe41-04fb-4666-8600-9e4e9244e672">
<img width="1152" alt="Screenshot 2023-08-28 at 11 39 50 AM" src="https://github.com/Fiserv/Support/assets/92183615/bce2cd4d-177a-47f1-b0f1-070b051d57d4">

**Comment by OZ-FS** [comment] 2023-08-28 18:44
@palanikumarfiserv please review and comment on this issue

**Comment by OZ-FS** [comment] 2023-09-05 21:14
Closing this isssue.

**Closed by OZ-FS** 2023-09-05 21:14 UTC
Labels: bug, FirstVisionAPAC
