### ISSUE TITLE
Tenant Onboarding

### ISSUE THREAD

**Issue by f7wau03** [Fiserv/Support#315] opened 2023-02-16 21:18 UTC
## Name of the product / tenant:
Connected Commerce (uCom)

## Type of Tenant:
Specify the type of integration needed. Is it Full service, Doc Only or Link Out ?

Docs and mock apis

## GitHub Essentials:
These are required for Developer Studio team to create the GitHub repository.

### Team members:
Provide the GitHub usernames registered with Fiserv email address.

f7wau03 - Lakshminarayanan.Cunniputhurravi@fiserv.com
ebramk12 - ebram.kerolos@fiserv.com

### Suppport contacts: 
Provide fiserv email addresses below
   - Bug Reporting:
      Assignees: tony.stark@fiserv.com, captain.america@fiserv.com
   - Feedback Reporting:
      Assignees: tony.stark@fiserv.com, captain.america@fiserv.com
   - Enhancement Reporting:
      Assignees: tony.stark@fiserv.com, captain.america@fiserv.com 

## Studio Essentials:
These are required for Developer Studio team to create the GitHub repository.

### External Link:
Provide the external link to your product or developer portal if you chose "Link Out" as the "Type of tenant"

### Internal: 
Is this product only for Fiserv's Internal use. Answer 'Yes / No'. If not sure please leave it as 'No'

NO

### Carat:
Is it a product of Fiserv's carat solutions. Answer 'Yes / No'. If not sure please leave it as 'No'

YES

### Solution Areas: 
Which Solution would your product fit into? 
- Merchants:
        SMB: Yes 
        Enterprise: Yes 
- Financial instustions:
        Banks: No 
        Credit Untions: No 
        Large financial instutitions: No
- Fintech: No

### Filter Tags:
Specify tags to filter your product
#### Region of Operation:
   - North America: Yes / No
   - EMEA: Yes / No
   - LATAM: Yes / No
   - APAC: Yes / No
      
#### Integration:
   - restful: Yes
   > Developer Studio needs restful APIs for integration.
   - sdk: No

#### Industry:
What industry sectors does your product target? 
Example: "Retail", "Banking", "Petroleum"

## Runbox Essentials:
Below information is required for the running the APIs on Developer Studio

### Runbox:
Do you want to enable the run box feature? Answer "Yes / No". Yes

> If the preceding response is "Yes," continue filling out the below sections:

#### Type of Sandbox:
- Mock : Yes
- Live: No 

> Please note that the Live sandbox setting overrules mock setting. Developer Studio team will later connect with you to collect Live server connectivity details.

> If Live sandbox is not ready at your end, Developer Studio will provide a Mock server for your APIs. For that please change the above value of 'Mock' to 'Yes'.

**Comment by sfiserv** [comment] 2023-02-16 21:25
@f7wau03 Ucomm or Connected Commerce is already on boarded as full tenant on DevStudio's Dev env
<img width="1559" alt="image" src="https://user-images.githubusercontent.com/87097017/219490088-40fa3f3e-1a60-4141-b988-d61513c804b2.png">
https://dev-developer.fiserv.com/product/ConnectedCommerce/api/?type=post&path=/v1/customers/{fdCustomerId}/provisions&branch=develop&version=1.0.0
hence closing this ticket.
If you have any new requirement you can please create a new issue

**Closed by sfiserv** 2023-02-16 21:25 UTC
Labels: Onboard New Tenant

**Comment by f7wau03** [comment] 2023-02-16 21:31
Can you please let me know what kind of issue I need to create for Staging & production deployment of the same?

**Comment by sfiserv** [comment] 2023-02-17 00:41
Create a new issue  using this url
https://github.com/Fiserv/Support/issues
To enable your product in QA, Stage, and Production.
Once the issue is created our team will priortize it in our upcoming sprints and the progressed to the upper environment according to our Deployment schedule.
