### ISSUE TITLE
All the Inquiry endpoints get disappear

### ISSUE THREAD

**Issue by sivabonjour** [Fiserv/Support#162] opened 2022-06-29 09:15 UTC
# Reporting new issue for [NAME] (Tenant/Product)
signature-international

**Region** (if applicable)
LATAM

**Page**
https://dev-developerstudio.fiserv.com/product/SignatureInternational

**Describe the bug**
We have 8 endpoints defined in Savings and all the x-group-name, x-proxy-name and x-child-product-name defined as per portal document. However, only 2 endpoints are getting displayed and not sure what is the reason. 

The links to the savings.yaml file from Git repo tenant :
([https://github.com/Fiserv/signature-international/blob/develop/reference/2.2/Savings%20Account/savings.yaml]

The link where the API is getting dispaled.
[https://dev-developerstudio.fiserv.com/product/SignatureInternational]

**To Reproduce**
1. Please check the YAML definition in ([https://github.com/Fiserv/signature-international/blob/develop/reference/2.2/Savings%20Account/savings.yaml] that has 8 endpoints
2. Please check the dev portal which has only 2 endpoints getting dispalyed [https://dev-developerstudio.fiserv.com/product/SignatureInternational]

**Expected behavior**
All the endpoints defined in YAML should be displayed. This is the same problem for all our services. 

**Screenshots**
![image](https://user-images.githubusercontent.com/100300230/176399482-303e876f-38dd-4252-ba0d-fcdb16a7b8fa.png)

![image](https://user-images.githubusercontent.com/100300230/176399596-ca1010bf-fac7-4668-a441-991e24874715.png)

![image](https://user-images.githubusercontent.com/100300230/176399713-73c3d38e-5d36-482d-8111-39db33420965.png)

**Desktop (please complete the following information):**
 - Chrome in Windows 10 laptop

**Tablet (please complete the following information):**
 -N/A

**Smartphone (please complete the following information):**
 -N/A

**Additional context**
 -N/A

**Comment by TaniaSarkar89** [comment] 2022-07-05 15:49
Created a Jira Issue
https://firstdatateam.atlassian.net/browse/PORT-4536

**Comment by TaniaSarkar89** [comment] 2022-07-18 15:24
Hi @sivabonjour we looked into the issue and looks like the issue is not with the x-elements. Right now Dev Studio displays a maximum of 200 APIs at the most. Displaying Signature International's 622 APIs would need development effort from our end while making sure it does not taking a hit to the site's performance. This fix would take some time as we design a more stable and efficient system.

However we are prioritizing this issue and we will keep our progress updated here for your reference. Also this is a duplicate Github ticket : https://github.com/Fiserv/Support/issues/163 hence closing this ticket. We will be tracking the progress in the other ticket and closing this one.

Thanks!

**Closed by TaniaSarkar89** 2022-07-18 15:24 UTC
Labels: bug, Priority - Low, Severity - Low

**Comment by SandeepP2** [comment] 2022-07-26 14:10
could we get a timeline for resolution please?

**Comment by TaniaSarkar89** [comment] 2022-07-26 17:36
Hi @SandeepP2 we are redesigning and restructuring our existing API explorer tree and this new design would take at least 3 sprints for us to implement as it a high-impacting story.

We would keep you posted on our progress.

Thanks!

Cc: @Yelena11  @rajeshb15
