### ISSUE TITLE
Request for prism mock server

### ISSUE THREAD

**Issue by pavelbelousov** [Fiserv/Support#672] opened 2024-04-12 19:51 UTC
Hello.

We will need some help to create and do configuration for prism mock server for our devstudio project https://github.com/Fiserv/ipg-na.
Please let know if you will need any additional information from us.

Thanks.

**Comment by minh-pham1** [comment] 2024-04-12 20:00
Hello Pavel! As per the default configurations, you already are using our Prism mock server. When you click Run Request, the request with the header and body is being sent to our mock server in the backend and returning the mock response (as defined by the reference yamls made in your Github.

Is there any additional requests or issues you have seen with the current configuration?

**Comment by pavelbelousov** [comment] 2024-04-12 20:06
Hello. It does not work on https://developer.fiserv.com/product/IPGNA or on https://qa-developer.fiserv.com/product/IPGNA. When I submit request I do not have proper response back. When I test it locally, everything is working as exspected.
Please advice.

Thanks.
![Screenshot 2024-04-12 at 4 03 06 PM](https://github.com/Fiserv/Support/assets/149000855/ced884aa-30ee-4cdf-9d28-07eb63cbcf8e)
![Screenshot 2024-04-12 at 4 03 30 PM](https://github.com/Fiserv/Support/assets/149000855/1fde5ec6-8d54-4682-9029-4d4ada609f7e)

**Comment by pavelbelousov** [comment] 2024-04-12 20:08
![Screenshot 2024-04-12 at 4 07 31 PM](https://github.com/Fiserv/Support/assets/149000855/1367d393-a396-4b02-8e69-964e49b0a701)
 The local test with prism server...

**Comment by pavelbelousov** [comment] 2024-04-12 20:16
@minh-pham1 Locally I am using additional attribute in header (Prefer example="NAME OF EXAMPLE")
I do not see on how it can be injected in case of devstudio deployment. 

Any advice?

**Comment by minh-pham1** [comment] 2024-04-12 20:35
For headers, I believe there is a way to configure it to show up under `Parameters` tab and included as part of the request. I'll assign it to @russnicoletti who might be able to give you better insight and help.

**Comment by russnicoletti** [comment] 2024-04-16 00:00
@pavelbelousov My apologies for not responding sooner. I have not been able to look into this. I will do so during my day tomorrow.

**Comment by pavelbelousov** [comment] 2024-04-17 15:47
@russnicoletti Any update on my issue?

**Comment by russnicoletti** [comment] 2024-04-17 22:39
Hello @pavelbelousov, I have verified the `account-verification` API returns a proper response with our mock sandbox. However, your tenant is currently configured to use a 'live' sandbox. I have changed it to use our mock (prism) sandbox but the change will not take affect immediately. It will take affect at the latest tomorrow morning PST. I will update you when the change has taken affect and I will verify the API is successful in our dev environment. For which environments would you like to use our mock server?

**Comment by pavelbelousov** [comment] 2024-04-18 14:34
@russnicoletti Thanks for update. I usually do changes in preview branch and than propagate it to others.
Preview -> Develop -> Stage -> Main
So Are you saying that we can use mock server only for specific environment?

**Comment by russnicoletti** [comment] 2024-04-18 17:43
@pavelbelousov We have Developer Studio environments that roughly correspond to the GitHub branches. `dev` (`develop` branch), `qa` (also `develop` branch when the branch has passed QA), `stage` (`stage` branch), `prod` ('main` branch). Each environment has a separate configuration such that tenants can choose in which environments they want a "mock" sandbox or "live" sandbox. Most tenants have the same configuration for each environment but it's not required. You can have a "mock" sandbox in the `dev` and `qa` environments and "live" in `stage` and `prod`. In any event, you can decide and we will update the configuration accordingly.

**Comment by russnicoletti** [comment] 2024-04-18 17:45
I did verify your APIs (I tested the `account-verification` API) work properly in our `dev` environment using the mock sandbox.
![Screenshot 2024-04-18 at 10 33 36 AM](https://github.com/Fiserv/Support/assets/5983096/c0c045f5-a028-4a04-ba58-b0a5ccd86881)
![Screenshot 2024-04-18 at 10 44 32 AM](https://github.com/Fiserv/Support/assets/5983096/616c019b-c04a-4061-9bb7-d61d792090a6)

**Comment by minh-pham1** [comment] 2024-04-30 18:48
Revalidated on dev and awaiting hotfix

**Comment by pavelbelousov** [comment] 2024-05-02 15:56
Any update for it?

**Comment by russnicoletti** [comment] 2024-05-03 21:44
Hello @pavelbelousov, your APIs are now working with our mock server in the `qa` environment. It will be approximately two weeks until the configuration changes are made to the `stage` environment.

**Comment by pavelbelousov** [comment] 2024-05-06 14:32
@russnicoletti Can you verify that this is a normal behavior? Examples are working fine in QA devportal. When I click on "Run Request" button, I can see expected result and button become disabled. If I click on Request tab, I can see dropdown with request example and button become enabled. I can change request type from dropdown, but can not execute, because "Run Request" button stop working. The only work around is to refresh browser page for executing example again. Do we have a bug in the devportal or this is a expectable behavior?

CC: @minh-pham1

**Comment by minh-pham1** [comment] 2024-05-06 22:05
Hello Pavel!

The run request box on the right (which I'll call Runbox) has 2 tabs, Request and Response. You can only trigger `Run Request` in the Runbox if the `Runbox Request` tab is open.

On the main screen there are 4 tabs. The first two tabs (`Parameters` and `Request Schema`) will automatically open the `Runbox Request`, which will allow you to click `Run Request`. The last two tabs (`Response Schema` and `Response Codes`) will automatically open the `Runbox Response` which will not allow you to click `Run Request`.

You can, of course, change the `Runbox` tab back to "Request" in order to re-enable the `Run Request` button. I'm not sure exactly what the issue you're facing is. Could you add a screenshot or screen recording if possible?

Here are the two cases I have described.
![Screenshot 2024-05-06 at 2 56 03 PM](https://github.com/Fiserv/Support/assets/114534554/ac6dde97-36cc-4565-8e1b-1978dbb49342)
![Screenshot 2024-05-06 at 2 56 12 PM](https://github.com/Fiserv/Support/assets/114534554/967c71f6-c3f4-4510-9b51-50ccb017ea32)

**Comment by pavelbelousov** [comment] 2024-05-07 15:20
@minh-pham1 I can not execute second request when I click on "Run Request" button.
1. Click on Request tab and select request payload example.
![1-request](https://github.com/Fiserv/Support/assets/149000855/7c1f63d4-215e-49a4-becd-b0f21aa0701e)
2. Click on "Run Request" button. I can see correct response example payload and "Run Request" button become disabled.
![1-response](https://github.com/Fiserv/Support/assets/149000855/a0731ba7-205e-4023-a7dc-974f221c787c)
3. Click on Request tab for executing different example payload. After that select different payload from dropdown. The "Run Request" button become enabled.
![2-request](https://github.com/Fiserv/Support/assets/149000855/73522709-5f6a-4e44-8b77-6fa2f05d880a)
4. Try to click on "Run Request" button, but devportal does not execute second request. Only full screen refresh can reset functionality on screen and I can execute different example.

**Comment by russnicoletti** [comment] 2024-05-07 16:16
Hello @pavelbelousov, I am able to reproduce the issue you describe. This issue affects all tenants. I will bring it to the attention of the team. Thanks for reporting it.

**Comment by russnicoletti** [comment] 2024-05-07 16:22
Another way to work around this issue is to select a different API, then select again the API you'd like to execute. I realize this is inconvenient and I don't consider it a permanent solution but it may be less inconvenient than reloading the UI.

**Comment by russnicoletti** [comment] 2024-05-07 16:23
https://firstdatateam.atlassian.net/browse/PORT-11116

**Comment by pavelbelousov** [comment] 2024-05-07 18:09
@russnicoletti Thanks for confirming this issue. I will explain this limitation and work around to my team. Please let us know if it will be fixed at some point of time.

**Comment by pavelbelousov** [comment] 2024-05-09 15:18
@minh-pham1 @russnicoletti I have a different question about GET API. For example "/store/availableIsoCountries". I did not see any instruction on how it can be setup in yaml in order to work for devportal "Run Request" button.  When I test it locally it works fine, but when I try to do the same in devportal I can see blank page after I click on "Run Request" button.
![Screenshot 2024-05-09 at 11 12 25 AM](https://github.com/Fiserv/Support/assets/149000855/383f1d41-df00-493f-b75b-d598f0614e2c)
![Screenshot 2024-05-09 at 11 12 51 AM](https://github.com/Fiserv/Support/assets/149000855/186034ce-68fe-40e8-a777-fe0841a8e6a8)
Any advice on it?

**Comment by russnicoletti** [comment] 2024-05-09 20:27
Hello @pavelbelousov, I am able to reproduce what you describe. In addition to GET /store/availableIsoCountries, the same behavior happens with GET /store/availableCurrencies. However, GET /orders/{order-id} works properly. I will create a bug ticket. I apologize for the inconvenience.

**Comment by russnicoletti** [comment] 2024-05-09 20:43
https://firstdatateam.atlassian.net/browse/PORT-11140

**Comment by pavelbelousov** [comment] 2024-05-17 14:53
Hello @russnicoletti any update on?
https://firstdatateam.atlassian.net/browse/PORT-11116
https://firstdatateam.atlassian.net/browse/PORT-11140

**Comment by russnicoletti** [comment] 2024-05-17 15:55
Hi @pavelbelousov, these issues are scheduled for next week. I will let you know when there is an update.

**Comment by pavelbelousov** [comment] 2024-05-29 13:39
Hello @russnicoletti any update on?
https://firstdatateam.atlassian.net/browse/PORT-11116
https://firstdatateam.atlassian.net/browse/PORT-11140

**Comment by russnicoletti** [comment] 2024-05-29 16:32
https://firstdatateam.atlassian.net/browse/PORT-11140<https://urldefense.com/v3/__https:/firstdatateam.atlassian.net/browse/PORT-11140__;!!P9vvK-4S!iaW0AIjL2k01OqjBa-NG7uq-SlxJr_k3U8k_F2QCdNnDlpLD3_2GyOTfhUBe9u-Iryv_yVBRQXbqQAOOeTYgViZqgxiZu70$> is being investigated this sprint.

https://firstdatateam.atlassian.net/browse/PORT-11116<https://urldefense.com/v3/__https:/firstdatateam.atlassian.net/browse/PORT-11116__;!!P9vvK-4S!iaW0AIjL2k01OqjBa-NG7uq-SlxJr_k3U8k_F2QCdNnDlpLD3_2GyOTfhUBe9u-Iryv_yVBRQXbqQAOOeTYgViZqp3IsqNg$> is a duplicate of https://firstdatateam.atlassian.net/browse/PORT-10959, which is being investigated next sprint (the two weeks starting next week)

Russ Nicoletti
Senior Software Engineer
Digital Innovation & Transformation
***@***.******@***.***>



From: pavelbelousov ***@***.***>
Date: Wednesday, May 29, 2024 at 6:39 AM
To: Fiserv/Support ***@***.***>
Cc: Nicoletti, Russ (Sunnyvale) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Request for prism mock server (Issue #672)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


Hello @russnicoletti<https://urldefense.com/v3/__https:/github.com/russnicoletti__;!!P9vvK-4S!iaW0AIjL2k01OqjBa-NG7uq-SlxJr_k3U8k_F2QCdNnDlpLD3_2GyOTfhUBe9u-Iryv_yVBRQXbqQAOOeTYgViZq3FnVxwI$> any update on?
https://firstdatateam.atlassian.net/browse/PORT-11116<https://urldefense.com/v3/__https:/firstdatateam.atlassian.net/browse/PORT-11116__;!!P9vvK-4S!iaW0AIjL2k01OqjBa-NG7uq-SlxJr_k3U8k_F2QCdNnDlpLD3_2GyOTfhUBe9u-Iryv_yVBRQXbqQAOOeTYgViZqp3IsqNg$>
https://firstdatateam.atlassian.net/browse/PORT-11140<https://urldefense.com/v3/__https:/firstdatateam.atlassian.net/browse/PORT-11140__;!!P9vvK-4S!iaW0AIjL2k01OqjBa-NG7uq-SlxJr_k3U8k_F2QCdNnDlpLD3_2GyOTfhUBe9u-Iryv_yVBRQXbqQAOOeTYgViZqgxiZu70$>

**Comment by pavelbelousov** [comment] 2024-06-03 15:45
Hello @russnicoletti . Can you provide approximate date when you think https://firstdatateam.atlassian.net/browse/PORT-11140 will be resolved?

**Comment by russnicoletti** [comment] 2024-06-03 18:32
Hello @pavelbelousov, the issue is resolved in our developer environment (dev-developer.fiserv.com). The fix will be in the qa environment in the next couple of days. It is scheduled to be in production the week of June 17.

**Comment by russnicoletti** [comment] 2024-06-06 19:07
Hi @pavelbelousov, this ticket https://firstdatateam.atlassian.net/browse/PORT-11116 is being tracked by this ticket https://firstdatateam.atlassian.net/browse/PORT-10959. The issue is fixed in the develop environment. The fix will be in the qa environment next week. It is scheduled to be in production the week of June 24.

**Comment by minh-pham1** [comment] 2024-07-15 22:13
Change seems to have been deployed and validated. Please feel free to reopen the ticket as needed, thank you!

**Closed by minh-pham1** 2024-07-15 22:13 UTC
