### ISSUE TITLE
Move TransferNow Tenant to Staging

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#592] opened 2023-12-20 06:40 UTC
### Context

1. We want to move TransferNow(TN) Tenant to Staging environment.

### Solution

1. We want to see TransferNow(TN) Tenant and all the content in TransferNow in Staging.

### Alternatives

We want to see TransferNow(TN) Tenant and all the content in TransferNow in Staging.

**Comment by sfiserv** [comment] 2023-12-21 07:18
Tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-9044

**Comment by minh-pham1** [comment] 2024-01-08 23:38
Hello @ManiBharathiNatarajan! The update scripts have been made and is being tracked. We will update the ticket when the stage deployment date is locked in. Thank you for your patience.

**Comment by ManiBharathiNatarajan** [comment] 2024-01-09 05:49
Hi @minh-pham1 Can you please consider this ticket as well (https://github.com/Fiserv/Support/issues/578) before moving it to staging environment.

**Comment by minh-pham1** [comment] 2024-01-09 20:36
> Hi @minh-pham1 Can you please consider this ticket as well (#578) before moving it to staging environment.

I have already accounted for that ticket. Thanks for double checking.

**Comment by minh-pham1** [comment] 2024-01-09 20:38
> Hi @minh-pham1 Can you please consider this ticket as well (#578) before moving it to staging environment.

I have already accounted for that ticket. Thanks for double checking.

**Comment by minh-pham1** [comment] 2024-01-10 23:50
Same note from #593.

> Hi Mani, just as a note, the `stage` environment will utilize the docs and APIs that are present on your product's Github `stage` branch. Please make sure to create a feature branch to push the files that are ready for staging/production. The files on your Github `develop` branch will not reflect on our `stage` environment.
> 
> Should your tenant wish to go to production at some point, you'll then also need to create feature branches to push from `stage` -> `main` on github.

**Comment by sfiserv** [comment] 2024-01-30 00:07
@ManiBharathiNatarajan  can you please confirm with your team that your product is ready to Production.
We need to know if you plan to stay in Stage environment or move to Production.
As per our process our Stage and Production environments need to be in sync. hence we cannot just enable your product in stage.

Also as mentioned by Minh we cannot enable your product in stage since you have not pushed your changes to stage branch.

**Comment by sfiserv** [comment] 2024-02-10 05:57
we have been communicating with the team on this issue. ( since they are not ready to go Production)The team's Business unit has not confirmed whether they want to go up to production.
Since Stage and Production needs to be in syn Developer studio cannot keep them enabled only in stage.
Closing this ticket now and will reopen once we hear from the tenant.

**Closed by sfiserv** 2024-02-10 05:57 UTC
Labels: enhancement, Priority - Medium, Transfer Now

**Comment by ManiBharathiNatarajan** [comment] 2024-03-27 09:14
Hi @minh-pham1, can you pl reopen the ticket, as we are ready to move to staging environment. 

Pl consider the following tickets as well. https://github.com/Fiserv/Support/issues/647, https://github.com/Fiserv/Support/issues/651, https://github.com/Fiserv/Support/issues/652, https://github.com/Fiserv/Support/issues/636
