### ISSUE TITLE
Enable Identity (Onboard Advisor) Provider Free Plan

### ISSUE THREAD

**Issue by AjitR01** [Fiserv/Support#471] opened 2023-08-14 15:37 UTC
### Context

Given Identity Onboard Advisor Provider & API are made available,
When Identity API Spec is promoted to DevStudio and Free plan Provider environment is onboarded,
Then it should be enabled in DevStudio Banking Hub space for a user to created free plan api credentials for Identity Onboard Advisor.

### Solution

Enabled Free Plan Identity Onboard Advisor in DevStudio Banking Hub space

### Alternatives

N/A

### Additional Context

![image](https://github.com/Fiserv/Support/assets/137955475/e924d706-21aa-437c-ade3-b627ef421efb)

### Region

https://developer.fiserv.com/workspace/

**Comment by sfiserv** [comment] 2023-10-11 22:16
Closing this issue since Bankinghub team has verified and confirmed this issue as fixed.

**Closed by sfiserv** 2023-10-11 22:16 UTC
Labels: enhancement, BankingHub
