### ISSUE TITLE
Document explorer not showing more than 3 levels

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#346] opened 2023-03-15 21:47 UTC
# Reporting new issue for First Vision LATAM

**Region** (if applicable)
LATAM

**Page**
Document explorer

**Describe the bug**
When document explorer contain more than 3 levels, Portal doesn't show next levels and in products when are needed to add more than one product or region reduces the possibility to show the information as the solution requires.

**To Reproduce**
1. Add more than 3 levels to show in document explorer
2. Go to Documentation Explorer 
3. See error, Only first 3 levels are shown.

**Expected behavior**
That Portal supports more than 3 levels in documentation and

**Screenshots**
![image](https://user-images.githubusercontent.com/111396588/225451184-e2584606-6035-4638-820c-eb191704eea1.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment] 2023-03-15 22:17
We already have issue created for this and is prioritized to be worked on.
This is an enhancement not a bug.

**Comment by sfiserv** [comment] 2023-03-24 20:06
@CinthyaRivera please verify the changes for the 3 tiers.

**Comment by CinthyaRivera** [comment] 2023-03-27 21:11
In validation

**Comment by CinthyaRivera** [comment] 2023-04-12 15:37
@sfiserv Validated and works correctly with 3 tiers

**Comment by sfiserv** [comment] 2023-04-24 05:13
Closing this issue as the changes are validated and working as expected.

**Closed by sfiserv** 2023-04-24 05:13 UTC
Labels: enhancement, Priority - Medium, FirstVision Latam, client verification
