### ISSUE TITLE
Download API and PostMan Collection not working

### ISSUE THREAD

**Issue by prabaharanthommai** [Fiserv/Support#650] opened 2024-03-22 10:58 UTC
In API Explorer Download API and Download PostMan Collection not working, while downloading showing Error

![image](https://github.com/Fiserv/Support/assets/145688917/6d42cd3c-1a06-4f4a-8d5e-60db53cec645)

**Comment by minh-pham1** [comment] 2024-03-22 15:34
Hello @prabaharanthommai! We have identified the issue and the fix is being tracked as part of https://firstdatateam.atlassian.net/browse/PORT-10269.

The issue should be fixed by the end of Monday after our `qa` deployment, I'll be sure to update you here. Apologies for any inconvenience!

**Comment by minh-pham1** [comment] 2024-03-26 22:33
Hello @prabaharanthommai! The issue should now be fixed on our `qa` environment. Please verify and close the ticket if the issue is resolved. Thank you for your patience!

**Comment by minh-pham1** [comment] 2024-04-11 22:13
Marking as complete due to inactivity and work being done on our side.

**Closed by minh-pham1** 2024-04-11 22:13 UTC
Labels: bug, client verification
