### ISSUE TITLE
Move VerifyNow(VN) Tenant to Staging

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#593] opened 2023-12-20 06:46 UTC
### Context

We want to move VerifyNow(VN) Tenant to Staging environment.

### Solution

We want to move VerifyNow(VN) Tenant and all the content in VerifyNow to Staging.

### Alternatives

We want to move VerifyNow(VN) Tenant and all the content in VerifyNow to Staging.

**Comment by sfiserv** [comment] 2023-12-21 07:19
tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-9044

**Comment by minh-pham1** [comment] 2024-01-08 23:38
Hello @ManiBharathiNatarajan! The update scripts have been made and is being tracked. We will update the ticket when the stage deployment date is locked in. Thank you for your patience.

**Comment by ManiBharathiNatarajan** [comment] 2024-01-09 14:02
Hi @minh-pham1 Thank you for the update. Can you pl check and consider https://github.com/Fiserv/Support/issues/594 this ticket as well.

**Comment by minh-pham1** [comment] 2024-01-10 00:06
Noted, will be updated accordingly on for the scripts for stage. Thank you for letting me know!

**Comment by ManiBharathiNatarajan** [comment] 2024-01-10 10:29
Hi @minh-pham1, Could you pl provide your insights as well, if possible pl consider this ticket also https://github.com/Fiserv/Support/issues/559

**Comment by minh-pham1** [comment] 2024-01-10 20:32
> Hi @minh-pham1, Could you pl provide your insights as well, if possible pl consider this ticket also #559

That is an unrelated issue. Assignment and comments will be on that ticket separately from this.

**Comment by minh-pham1** [comment] 2024-01-10 23:49
Hi Mani, just as a note, the `stage` environment will utilize the docs and APIs that are present on your product's Github `stage` branch. Please make sure to create a feature branch to push the files that are ready for staging/production. The files on your Github `develop` branch will not reflect on our `stage` environment.

Should your tenant wish to go to production at some point, you'll then also need to create feature branches to push from `stage` -> `main` on github.

**Comment by sfiserv** [comment] 2024-02-10 05:55
we have been communicating with the team on this issue. ( since they are not ready to go Production)The team's Business unit has not confirmed whether they want to go up to production. 
Since Stage and Production needs to be in syn Developer studio cannot keep them enabled only in stage.
Closing this ticket now and will reopen once we hear from the tenant.

**Closed by sfiserv** 2024-02-10 05:55 UTC
Labels: enhancement, Priority - Medium, VerifyNow

**Comment by ManiBharathiNatarajan** [comment] 2024-03-27 09:14
Hi @minh-pham1, can you pl reopen the ticket, as we are ready to move to staging environment. 

Pl consider the following tickets as well. https://github.com/Fiserv/Support/issues/647, https://github.com/Fiserv/Support/issues/651, https://github.com/Fiserv/Support/issues/652
