### ISSUE TITLE
 - Prod Environment Dissapear

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#671] opened 2024-04-12 15:31 UTC
### Product

First Vision Latam

### Page

https://developer.fiserv.com/product/FirstVisionLATAM?branch=main

### Description

First Vision Latam Tenant dissapear from prod env.

Also dissapear from catalog.

![image](https://github.com/Fiserv/Support/assets/111396588/8bf797cc-9617-4615-9a66-4fd2fc61c619)

### Expected Behaviour

Show Tenant

### Operating system

Windows

### Browser

Chrome

### Region

LATAM

**Comment by Rezi0110** [comment] 2024-04-12 16:21
Hello Cinthya,
 Thank you for reporting this bug, we have found the problem and are currently working on the solution, we will keep you updated as we make progress with bringing back FirstVision - LATAM onto prod.

**Comment by sfiserv** [comment] 2024-04-12 17:00
@CinthyaRivera our team has identified the problem and are applying the fix. Your tenant should be back within 30 minutes

**Comment by Rezi0110** [comment] 2024-04-12 17:34
Hello @CinthyaRivera, FirstVision - LATAM is back on prod environment, and functioning as intended, please check on your side, and do let us know if you run into any further issues, we are sorry for the inconvenience this may have caused for your team.

**Comment by minh-pham1** [comment] 2024-04-25 20:53
Closing ticket as issue has been resolved

**Closed by minh-pham1** 2024-04-25 20:53 UTC
Labels: bug, client verification
