### ISSUE TITLE
Navigation link is not visible under API explorer (Dev Studio)

### ISSUE THREAD

**Issue by Basant9** [Fiserv/Support#217] opened 2022-10-19 07:41 UTC
# Reporting new issue for [Dev Studio] (Tenant/Product)

Navigation link is not visible.

**Region** (if applicable) - 
We are validating the changes on UAT environment. Due to the issues we are not able to check.

**Page**
https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC

There were three components in API explorer. But all are missing. 
 
**Describe the bug**
Earlier there were three components under API explorer. The components are 1. Merchant Onboarding , 2. Cloud based integration , 3. Local based integration.  Now those components are not visible. 

**To Reproduce**
1. Go to 'https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC'
2. Click on 'API Explorer'
3. Scroll down to 'Components'
4. See error  - Components are not visible.

**Expected behavior**

All component should visible.
**Screenshots**
![image](https://user-images.githubusercontent.com/115777991/196626549-f506e3ed-d008-4a28-95ca-13a12fe5e5f0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome
 - Version :Version 106.0.5249.119

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment] 2022-10-21 04:50
Moving this ticket to milestone 22 and @TaniaSarkar89 to debug the issue and provide the root cause. Else Jira ticket will be created if this issue needs more efforts for fix.

**Comment by TaniaSarkar89** [comment] 2022-10-26 13:48
@Basant9 This [spec](https://github.com/Fiserv/acceptance-solutions-apac/blob/develop/reference/1.0.2/boarding-test.yaml) file has an issue. You need to fix the parser error for this and revalidate your spec file in [editor.swagger.io](https://editor.swagger.io/).

![image](https://user-images.githubusercontent.com/74629095/198043564-5e2248de-f634-46b9-9d5d-9a7dca9577c6.png)

Thanks!

**Closed** 2022-11-09 18:52 UTC
Labels: bug, Priority - Medium, Severity - Medium, AcceptanceSolutionsAPAC
