### ISSUE TITLE
Bill Pay Issue

### ISSUE THREAD

**Issue by mlash912** [Fiserv/Support#244] opened 2022-12-01 17:52 UTC
# Reporting new issue for Trust FCU, Chattanooga, TN

**Region** (if applicable)
Tennessee

**Page**
https://trustfcu.com/

**Describe the bug**
I think maybe someone forgot to enable the ability to "pay a person" via Bill Pay using the payee's financial institutions routing and account number. 

**To Reproduce**
1. Go to 'www.trustfcu.com'
2. Login to Billpay
3. Add a Payee (Choose person)
4. Look at the information requested--missing option of entering routing number/account number.

**Expected behavior**
This should be enabled to allow folks to add when they are entering the information of a new payee(person).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIN
 - Browser CHROME
 - Version 

**Additional context**

**Comment by sfiserv** [comment] 2022-12-01 17:55
@mlash912 this github support is meant for issues related to DevStudio application only. Please reach out to the Trustcfu support team for their issues.
This issue is not relevant to DevStudio hence closing it.

**Closed by sfiserv** 2022-12-01 17:55 UTC

**Comment by mlash912** [comment] 2022-12-01 18:02
How is it not relevant?

Michael K. Lashley, Educator/Librarian;
Fixed Asset Manager;
Chromebook Manager;
Google Domain Administrator;
Technical Contact

Brainerd High School
1020 N. Moore Road
Chattanooga, TN 37411
(423) 855-2615 (Tel)
(423) 855-2651 (Fax)



________________________________

**Comment by sfiserv** [comment] 2022-12-01 18:41
@mlash912 we would like to help you or answer your queries if the issue was found on our application https://developer.fiserv.com/
we do not host the product Trust FCU on our application hence the issue is not relevant to DevStudio.

**Comment by mlash912** [comment] 2022-12-01 18:51
The product was FreeCheck and is now owned by Fiserv as it acquire MSN Money

Michael K. Lashley, Educator/Librarian;
Fixed Asset Manager;
Chromebook Manager;
Google Domain Administrator;
Technical Contact

Brainerd High School
1020 N. Moore Road
Chattanooga, TN 37411
(423) 855-2615 (Tel)
(423) 855-2651 (Fax)



________________________________

**Comment by sfiserv** [comment] 2022-12-01 19:13
@mlash912  please check out this support page for your queries, if you like. https://www.fiserv.com/en/about-fiserv/contact-us.html
As mentioned earlier DevStudio cannot help you further.
