### ISSUE TITLE
Title/Right Nav Pulled from Commented Out Header

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#440] opened 2023-07-26 13:58 UTC
### Product

Commerce Hub

### Page

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Debit/Regional-Debit.md

### Description

Regional Debit is commented out in the MD file, the Breadcrumbs and Right Nav are still listing it as the page name.

### Expected Behaviour

Commented information should not be rendered in markdown files

### Operating system

Windows

### Browser

Chrome, Edge

### Region

All

**Comment by sfiserv** [comment] 2023-08-09 04:17
Tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-7164

**Comment by afsharmiah15** [comment] 2023-08-29 20:05
Hi 
Can anyone kindly help me to understand what changes I have to make here? 
If anyone can reproduce the issue for me that would be great.

**Comment by wwfiserv** [comment] 2023-08-29 20:40
@afsharmiah15 if you look at the first item in the right nav it says Regional Debit which is commented out in the markdown file

![image](https://github.com/Fiserv/Support/assets/75692745/f37fe68c-3af4-4358-a728-c64378fc3868)

**Comment by afsharmiah15** [comment] 2023-09-01 18:21
Hi @wwfiserv 
As per discussion with one of our team member- Regional Debit is coming from the file> config/document-explorer-definition.yaml. where I can see Regional Debit is not commented out. Attached a screenshot for you. 

![image](https://github.com/Fiserv/Support/assets/142607773/c20ec006-6cda-44b6-a066-fb707e6bffb6)

If you comment  out the lines I mentioned above might resolve the issue. 
Kindly have a look into this. Let me know if you have any question for me.

**Comment by wwfiserv** [comment] 2023-09-05 13:40
@afsharmiah15 I'm not talking about the left nav (that is a separate update I have to push), I'm only talking about the breadcrumbs and right nav as displayed in the screenshots. I do not know how the breadcrumbs are derived, I assumed from the file structure and title (which as you showed is commented)

**Comment by minh-pham1** [comment] 2023-09-08 19:06
Hi William!

The left nav, breadcrumbs, and right nav first item are all related to the Title defined in the `document-explorer-definition.yaml`.

In theory, yes you can have a different H1 compared to the title of the document. However, as with this case, the left nav, right nav, and breadcrumbs will not match the content of the document itself. With regards to the right nav, the document name is shown as the first item on the list for quick navigation back to the top (in cases where the H1 matches the document title as expected). When the title doesn't match then it won't navigate (as expected).

As a follow-up question, which behavior would like like to investigate?
1. If you edit the `document-explorer-definition.yaml` to reflect a new document title, these fields should update themselves. (Current behavior)
2. You want the breadcrumbs and right nav to pull from first H1/title of the document. (Will need engineer to investigate feasibility and whether that fits within our design and functional architecture).

**Comment by wwfiserv** [comment] 2023-09-11 20:04
@minh-pham1 I don't think you understand what I'm saying, I have updated the documentation it has a different H1 that is visible, it has an old H1 (which I will remove but left in for your troubleshooting) that is still showing on the RIGHT nav and BREADCRUMBS. Nothing that is ever commented out in the documentation should ever be rendered in the elastic search or pages.

**Comment by minh-pham1** [comment] 2023-09-21 18:57
Hi William, sounds good. I just want to clarify where the fields are coming from just to level-set (Afsar is still assigned to this Jira issue, I'm just making sure that we all have the same understanding).

<img width="1259" alt="Screenshot 2023-09-21 at 11 28 22 AM" src="https://github.com/Fiserv/Support/assets/114534554/883ec0b9-7d3a-45e4-ab03-5f44be794591">

Essentially:
- Left nav: product-layout.yaml -> document title
- Breadcrumb: product-layout.yaml -> document title
- Right nav: First item = product-layout.yaml -> document title; Remaining Table of content items = H1-3

With this in mind, I see that the old H1 (that says Regional Debit) is no longer in the main document itself as you have noted. As for the breadcrumbs and right nav, they are fetching from the document information (on product-layout) so you'd have to modify the title if you want to update them. 

Is this solution acceptable or would you like to propose we add validation or other checks on DevStudio side to alter the breadcrumbs/right nav behavior?

**Comment by wwfiserv** [comment] 2023-09-21 19:02
@minh-pham1 the overall problem I was trying to bring to your team's attention is that our rendering agent should not do anything with commented out data. I would guarantee that if I leave the original H1 commented out and move it below the correct H1 it will properly display. Again I will be removing it but wanted to leave it in for your team to troubleshoot.

**Comment by minh-pham1** [comment] 2023-09-21 20:46
Ok, I will ask Afsar to look more into the issue and try to work through our ToC and Breadcrumb parsing logic again to double check how the data is generated and whether its properly excluding commented code.

**Comment by minh-pham1** [comment] 2023-09-21 21:08
Hi William, after some investigation it is as you mentioned. The issue will be fixed in the next sprint and move up into the QA env for validation in the future. I'll update this ticket once it's ready to be verified. Thank you for your help!

**Comment by sfiserv** [comment] 2024-02-10 06:27
@minh-pham1 please update this ticket if the fix is implemented and ready for verification.

**Comment by minh-pham1** [comment] 2024-02-12 18:09
Oh that is my bad, this fix should have been fixed on all environments since last year. Sorry for missing the update!

**Closed by minh-pham1** 2024-02-12 18:09 UTC
Labels: bug, documentation, CommerceHub, Priority - Medium, Severity - Low
