### ISSUE TITLE
Merchant Acquiring Latam tenant in Dev showing 503 error while trying to access the documentation

### ISSUE THREAD

**Issue by eascaniofsv** [Fiserv/Support#252] opened 2022-12-09 13:42 UTC
# Reporting new issue for Merchant Acquiring Latam

**Region** (if applicable): LATAM

**Page**: Tenant home page

**Describe the bug** Large "503" presented, with a message saying "We are having technical difficulties"

**To Reproduce**
1. Go to https://dev-developerstudio.fiserv.com/
2. Click on "Who we serve" and then "See all Merchants". Then click on Merchant Acquiring LATAM on the left side Menu
3. See error

**Expected behavior**
It should show the Merchant Acquiring LATAM home page, and the menu for documentation and API explorer on the left side

**Screenshots**
![image](https://user-images.githubusercontent.com/94861528/206715240-713ac7ea-24c4-49a1-9f1c-e8839a1ca576.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.99

**Comment by sfiserv** [comment] 2022-12-12 21:10
@eascaniofsv  our team has detected an error with your product layout yaml file. your team and team member (@CinthyaRivera ) has been informed about the issue in teams channel.
Please let us know once your team fixes the issue with file.

**Comment by sfiserv** [comment] 2022-12-12 22:12
@eascaniofsv  Seems the issue is fixed by your team hence closing this ticket.

**Closed by sfiserv** 2022-12-12 22:12 UTC
Labels: bug
