### ISSUE TITLE
APIs missing from API explorer

### ISSUE THREAD

**Issue by shubhamKanse99** [Fiserv/Support#322] opened 2023-02-23 09:33 UTC
# Reporting new issue for [firstvision-EMEA] (Tenant/Product)

**Region** (if applicable)
EMEA

**Page**
API explorer

**Describe the bug**

APIs are missing in API explorer. 

There are 4 yaml files in total for next 4 releases. 

23.02 - just went live, New API added here, v2/fppQuoteGeneration is missing from API explorer, but can be searched.
![image](https://user-images.githubusercontent.com/117971606/220867245-651c39d5-4b36-487c-ae0a-1a18b3386d9f.png)

23.03 - with v1/LostStolenUpdateLbg as a new API - missing, but can be searched.
![image](https://user-images.githubusercontent.com/117971606/220867468-8acf6438-e728-4e2d-b08e-416b764afb35.png)

23.04 - next release
23.06 - future release - All of the API changes from here are visible along with newly added APIs. (and this is marked as Major in config file.)

We want to display all of the APIs added in the swagger files for each release in the API explorer. 
If i click on, 23.03's- v1/LostStolenUpdateLbg new API in API explorer it should take me to it and version should change to 23.03 indicating that this API is going to be introduced as a part of 23.03 release.
![image](https://user-images.githubusercontent.com/117971606/220868230-78695deb-afa7-4483-9904-8ec80fa56b08.png)

This is our understanding that it should work this way. Please advice otherwise.

This is already impacting the clients so please help us resolve this asap.

**To Reproduce**
1. Go to 'search' on top right
2. Search for 'lostStolenUpdateLbg'
3. you will see this API listed there. 
4. Click on the API but it takes you to some other API.
5. when searched in API explorer, it is missing from there.

**Expected behavior**
 When I click on lostStolenUpdateLbg API it should take me to API explorer for this API and version should change to 23.03

**Screenshots**
Attached.

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment] 2023-02-24 05:28
@asingh2023 canyou please try to see what is the issue?

**Comment by sfiserv** [comment] 2023-03-10 04:29
the issue is resolved and marking it as done.

**Closed by sfiserv** 2023-03-10 04:29 UTC
Labels: bug, Priority - Medium, Severity - Low, Firstvision-Emea, verify bug
