### ISSUE TITLE
"Run Request" Button in API Explorer should not be enabled for Unauthenticated user.

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#613] opened 2024-01-17 09:30 UTC
### Product

VerifyNow

### Page

VerifyNow->API explorer

### Description

Run Request Button in API explorer Sandbox should be disabled for Unauthenticated Users.

### Expected Behaviour

Run Request Button in API explorer Sandbox should be enabled for only Authenticated Users.

### Operating system

Windows

### Browser

Google Chrome Version 120.0.6099.200

### Region

QA

**Comment by sfiserv** [comment] 2024-01-23 18:29
@ManiBharathiNatarajan can you please elaborate what your ask for authenticated user is.
and what is the ask. 
This is not a bug as you think , but an enhancement.

**Comment by ManiBharathiNatarajan** [comment] 2024-01-24 03:17
Hi @sfiserv, Thanks for the Confirmation. 
"Run Request" button should be disabled for Unauthenticated Users.
<img width="974" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/4eac7fe0-9da5-4fe1-950d-cf0f3fd029b0">

**Comment by minh-pham1** [comment] 2024-02-09 18:57
Hello Mani, is this a live service endpoint to your team's live API?

If it is a mock yaml, the request will not do anything except fetch the mock response from your yaml (just wanted to clarify just in case). 

However, if you would like a feature to only allow registered/authenticated users to try your live request in our API explorer then we'll mark this as an `enhancement` ticket and discuss it with our architects as needed.

**Comment by sfiserv** [comment] 2024-02-10 07:14
This is implementation cannot be done. This conflicts our engineering implementation. Hence closing this issue.

**Closed by sfiserv** 2024-02-10 07:14 UTC
Labels: VerifyNow
