### ISSUE TITLE
Limit value should be 3 but showing 0 on DevPortal 

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#115] opened 2022-03-17 13:49 UTC
# Reporting new issue for [Prepaid/UnclaimedPropertySearch] (Reporting)

**Page**
https://dev-developerstudio.fiserv.com/product/Reporting/api/?type=post&path=/v1/prepaid/unclaimedProperty/search

**Describe the bug**
The limit should be 3 in the request payload but on DevPortal its showing 0. But the swagger document is showing limit:3 but devportal is showing limit:0

**Screenshots: Attached the Screenshots from Swagger DOC**
<img width="1434" alt="Screen Shot 2022-03-17 at 9 48 27 AM" src="https://user-images.githubusercontent.com/84332702/158822907-a059ff0b-f1a8-4814-9af7-3c3095528f58.png">
If applicable, add screenshots to help explain your problem
<img width="851" alt="Screen Shot 2022-03-17 at 9 42 56 AM" src="https://user-images.githubusercontent.com/84332702/158822739-e4c865c6-c82c-48a0-b73b-d173525f5672.png">
.

<!-- ** Recommended **

- Assign a Bug 

    On you right hand side, you can set Assignees by Clicking setting button next to it.

**Comment by TaniaSarkar89** [comment] 2022-03-28 20:37
Opened a JIRA ticket to track this issue : https://firstdatateam.atlassian.net/browse/PORT-3840

**Comment by rajeshb15** [comment] 2022-04-08 15:17
@TaniaSarkar89 @kongaravinatha 
Example value is not available in the request schema.
https://dev-developerstudio.fiserv.com/product/Reporting/api/?type=post&path=/v1/prepaid/unclaimedProperty/search
![image](https://user-images.githubusercontent.com/80118847/162471471-529108eb-c37e-4365-8ef6-30ec945ba1a5.png)
Please update YAML ref with example value.( $ref: '#/components/schemas/PrepaidAccountSearchRequest')

And we have example value on "Transactions Search API" and it is getting displayed as expected.
https://dev-developerstudio.fiserv.com/product/Reporting/api/?type=post&path=/v1/prepaid/transactions/search
![image](https://user-images.githubusercontent.com/80118847/162471785-af7860e0-fc39-452e-9ddb-171835b248e4.png)

**Comment by sfiserv** [comment] 2022-05-12 05:52
The issue is fixed hence closing this issue.
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/87097017/168001194-4fdad14b-5651-4dad-9a3f-c566a5eadadc.png">

**Closed by sfiserv** 2022-05-12 05:52 UTC
Labels: bug, reporting
